budget = raw_input("What is your budget? ")
dates_to_explore = raw_input("When are you traveling?" )
time_allocation = raw_input("Start Location: ")
dest_neighborhood = raw_input("Which neighborhood in NYC would you like to visit? (ex. Upper West Side, Soho, etc.) ")
end_location = boolean(raw_input("Would you like to return to your start location? "))
